# Simple Kubernetes Pod to deploy the app contained in giacinto69/kubedemo:appv1
apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: web
spec:
  containers:
    - name: web-ctr
      image: giacinto69/kubedemo:appv1
      ports:
        - containerPort: 8080
